domain_path: C:\Users\Vick\Desktop\codesign\codesign_vitis\platform\export\platform\sw\standalone_psu_cortexa53_0
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
