domain_path: C:\Users\Vick\Desktop\codesign\codesign_vitis\platform\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
lang: c
