# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/zu3.xdc

# Block Designs: bd/codesign_vivado_bd/codesign_vivado_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==codesign_vivado_bd || ORIG_REF_NAME==codesign_vivado_bd} -quiet] -quiet

# IP: bd/codesign_vivado_bd/ip/codesign_vivado_bd_zynq_ultra_ps_e_0_0/codesign_vivado_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==codesign_vivado_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==codesign_vivado_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi4_half_adder_1_0/codesign_vivado_bd_axi4_half_adder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==codesign_vivado_bd_axi4_half_adder_1_0 || ORIG_REF_NAME==codesign_vivado_bd_axi4_half_adder_1_0} -quiet] -quiet

# IP: bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/codesign_vivado_bd_axi_smc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==codesign_vivado_bd_axi_smc_3 || ORIG_REF_NAME==codesign_vivado_bd_axi_smc_3} -quiet] -quiet

# Block Designs: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/bd_fac1.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_0/bd_fac1_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_1/bd_fac1_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_2/bd_fac1_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_3/bd_fac1_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_4/bd_fac1_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_5/bd_fac1_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_6/bd_fac1_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_7/bd_fac1_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_8/bd_fac1_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_9/bd_fac1_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_10/bd_fac1_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_11/bd_fac1_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_12/bd_fac1_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/codesign_vivado_bd/ip/codesign_vivado_bd_rst_ps8_0_96M_3/codesign_vivado_bd_rst_ps8_0_96M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==codesign_vivado_bd_rst_ps8_0_96M_3 || ORIG_REF_NAME==codesign_vivado_bd_rst_ps8_0_96M_3} -quiet] -quiet

# IP: bd/codesign_vivado_bd/ip/codesign_vivado_bd_xlconstant_0_0/codesign_vivado_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==codesign_vivado_bd_xlconstant_0_0 || ORIG_REF_NAME==codesign_vivado_bd_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_zynq_ultra_ps_e_0_0/codesign_vivado_bd_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_zynq_ultra_ps_e_0_0/codesign_vivado_bd_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==codesign_vivado_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==codesign_vivado_bd_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_1/bd_fac1_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_5/bd_fac1_s00a2s_0_ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_6/bd_fac1_sarn_0_ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_7/bd_fac1_srn_0_ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_8/bd_fac1_sawn_0_ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_9/bd_fac1_swn_0_ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_10/bd_fac1_sbn_0_ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/bd_0/ip/ip_11/bd_fac1_m00s2a_0_ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/ooc.xdc

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_axi_smc_3/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==codesign_vivado_bd_axi_smc_3 || ORIG_REF_NAME==codesign_vivado_bd_axi_smc_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/ip/codesign_vivado_bd_rst_ps8_0_96M_3/codesign_vivado_bd_rst_ps8_0_96M_3_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==codesign_vivado_bd_rst_ps8_0_96M_3 || ORIG_REF_NAME==codesign_vivado_bd_rst_ps8_0_96M_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Vick/Desktop/codesign/codesign_vivado/codesign_vivado.gen/sources_1/bd/codesign_vivado_bd/codesign_vivado_bd_ooc.xdc
